FROM anapsix/alpine-java
MAINTAINER venkat 
COPY NumberGenerator-1.0.1-SNAPSHOT.jar /home/NumberGenerator-1.0.1-SNAPSHOT
CMD ["java","-jar","/var/lib/jenkins/workspace/maven_job/target/myapp-3.0-SNAPSHOT.jar"]
